# Generated by Django 3.1 on 2020-08-15 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200815_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 15, 11, 17, 46, 300999), verbose_name='date published'),
        ),
    ]
