# Generated by Django 3.1 on 2020-08-16 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200816_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 20, 10, 52, 830081), verbose_name='date published'),
        ),
    ]
