# Generated by Django 3.1 on 2020-08-17 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200817_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 18, 2, 22, 334343), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 18, 2, 22, 335426)),
        ),
    ]
