# Generated by Django 3.1 on 2020-08-19 17:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_auto_20200817_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visit', models.DateTimeField()),
                ('last_request', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 17, 35, 16, 248879), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 17, 35, 16, 250018)),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
