# Generated by Django 3.1 on 2020-08-19 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200819_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 19, 14, 49, 987562), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 19, 14, 49, 988433)),
        ),
    ]
